# Deploy to github pages
# source: https://dev.to/madhust/how-to-publish-blazor-webassembly-application-to-github-pages-using-github-action-54h4

name: Deploy to Github Pages
env:
  PUBLISH_DIR: helple/bin/Release/net6.0/publish/wwwroot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
   push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Publish application
        run: dotnet publish -c Release

      # base href url value should be changed so that resources like CSS and scripts can load properly. 
      - name: Rewrite base href
        if: success()
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: ${{ env.PUBLISH_DIR }}/index.html
          base_href: REPOSITORY_NAME
          
      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. 
      # Allow files and folders starting with an underscore.
      - name: Add .nojekyll file
        run: touch ${{ env.PUBLISH_DIR }}/.nojekyll

      - name: Commit to GitHub pages Repo
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: ${{ env.PUBLISH_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
